import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
import { TransformControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/TransformControls.js';

const viewport=document.querySelector('#viewport');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x101215);
const camera=new THREE.PerspectiveCamera(55,1,.01,500); camera.position.set(7,6,9);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(viewport.clientWidth,viewport.clientHeight); renderer.shadowMap.enabled=true; viewport.appendChild(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement); orbit.enableDamping=true; orbit.target.set(0,1,0);
const transform=new TransformControls(camera,renderer.domElement); scene.add(transform.getHelper());
const hemi=new THREE.HemisphereLight(0xffffff,0x30343b,2.2); scene.add(hemi);
const key=new THREE.DirectionalLight(0xffffff,2.8); key.position.set(6,10,7); key.castShadow=true; scene.add(key);
const grid=new THREE.GridHelper(20,20,0x555b63,0x292d33); scene.add(grid);
const axes=new THREE.AxesHelper(2.5); scene.add(axes);
const objects=[]; let selected=null; let history=[]; let future=[];
const menuData={file:['New','Open…','Save','Save As…','Import 3D model…','Export','Print 3D'],edit:['Undo','Redo','Duplicate','Delete','Select All','Clear Selection'],view:['Home View','Top View','Front View','Right View','Perspective','Orthographic','Grid','Axes'],object:['Group','Ungroup','Combine','Subtract','Intersect','Split','Mirror'],insert:['Box','Sphere','Cylinder','Cone','Torus','Plane','Text','Image','Custom Mesh'],tools:['Measure','Align','Center','Smooth','Simplify','Repair','Material','Settings'],help:['Keyboard Shortcuts','Documentation','About 3D Builder']};
const menuPanel=document.querySelector('#menuPanel');

document.querySelectorAll('.menus button').forEach((b)=>b.addEventListener('click',(e)=>{const items=menuData[b.dataset.menu]; menuPanel.innerHTML=items.map((x,i)=>`<div class="menu-item" data-action="${x}">${x}</div>${[6,8,13].includes(i)?'<div class="menu-sep"></div>':''}`).join(''); menuPanel.style.left=b.getBoundingClientRect().left+'px'; menuPanel.classList.toggle('hidden'); menuPanel.querySelectorAll('.menu-item').forEach(item=>item.onclick=()=>runMenu(item.dataset.action));}));
document.addEventListener('click',(e)=>{if(!e.target.closest('.menus')&&!e.target.closest('#menuPanel'))menuPanel.classList.add('hidden')});

function geometryFor(type){switch(type){case'box':return new THREE.BoxGeometry(2,2,2);case'sphere':return new THREE.SphereGeometry(1.15,40,24);case'cylinder':return new THREE.CylinderGeometry(1,1,2,40);case'cone':return new THREE.ConeGeometry(1.15,2.2,40);case'torus':return new THREE.TorusGeometry(.8,.28,18,48);case'plane':return new THREE.PlaneGeometry(2.5,2.5);default:return new THREE.BoxGeometry(2,2,2)}}
function addObject(type){const mat=new THREE.MeshStandardMaterial({color:0x9aa3ad,roughness:.55,metalness:.08}); const mesh=new THREE.Mesh(geometryFor(type),mat); mesh.castShadow=true; mesh.receiveShadow=true; mesh.position.y=type==='plane'?0:1; mesh.name=type[0].toUpperCase()+type.slice(1)+' '+(objects.length+1); scene.add(mesh); objects.push(mesh); select(mesh); pushHistory(); updateList(); status('Added '+mesh.name);}
function select(obj){selected=obj||null; transform.detach(); if(obj){transform.attach(obj); updateInputs();} updateList(); updateProperties();}
function updateList(){const el=document.querySelector('#objectList'); el.innerHTML=objects.length?objects.map((o,i)=>`<div class="object-item ${o===selected?'selected':''}" data-index="${i}"><span>◇ ${o.name}</span><span>${o.visible?'':'hidden'}</span></div>`).join(''):'<div class="empty">No objects yet</div>'; el.querySelectorAll('.object-item').forEach(x=>x.onclick=()=>select(objects[+x.dataset.index]));}
function updateProperties(){const el=document.querySelector('#properties'); if(!selected){el.innerHTML='<div class="empty">Select an object</div>';return} el.innerHTML=`<div class="prop-row"><span>Name</span><strong>${selected.name}</strong></div><div class="prop-row"><span>Type</span><strong>${selected.geometry.type}</strong></div><div class="prop-row"><span>Vertices</span><strong>${selected.geometry.attributes.position.count}</strong></div><div class="prop-row"><span>Visible</span><strong>${selected.visible?'Yes':'No'}</strong></div>`;}
function updateInputs(){if(!selected)return;[['posX',selected.position.x],['posY',selected.position.y],['posZ',selected.position.z],['rotX',THREE.MathUtils.radToDeg(selected.rotation.x)],['rotY',THREE.MathUtils.radToDeg(selected.rotation.y)],['rotZ',THREE.MathUtils.radToDeg(selected.rotation.z)],['scaleX',selected.scale.x],['scaleY',selected.scale.y],['scaleZ',selected.scale.z]].forEach(([id,v])=>document.getElementById(id).value=Number(v).toFixed(2));}
['posX','posY','posZ','rotX','rotY','rotZ','scaleX','scaleY','scaleZ'].forEach(id=>document.getElementById(id).addEventListener('change',()=>{if(!selected)return; const v=+document.getElementById(id).value; if(id.startsWith('pos'))selected.position[id[3].toLowerCase()]=v; else if(id.startsWith('rot'))selected.rotation[id[3].toLowerCase()]=THREE.MathUtils.degToRad(v); else selected.scale[id[5].toLowerCase()]=v; pushHistory(); updateProperties();}));
transform.addEventListener('dragging-changed',e=>orbit.enabled=!e.value); transform.addEventListener('objectChange',()=>{updateInputs();updateProperties();});

document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addObject(b.dataset.add));
document.querySelectorAll('.tool[data-tool]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool[data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active');transform.setMode(b.dataset.tool==='select'?'translate':b.dataset.tool);status(b.dataset.tool==='select'?'Selection tool':b.dataset.tool+' tool');});
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;const r=renderer.domElement.getBoundingClientRect();const mouse=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);const ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(objects,false)[0]; if(hit)select(hit.object);});
function snapshot(){return objects.map(o=>({name:o.name,pos:o.position.toArray(),rot:o.rotation.toArray(),scale:o.scale.toArray(),type:o.geometry.type}));}
function pushHistory(){history.push(JSON.stringify(snapshot()));if(history.length>30)history.shift();future=[];}
function restore(s){objects.splice(0).forEach(()=>{});scene.traverse(o=>{if(o.isMesh&&objects.includes(o))scene.remove(o)});/* state restoration is expanded in later editor modules */}
function runMenu(a){menuPanel.classList.add('hidden'); if(a==='New'){objects.slice().forEach(o=>scene.remove(o));objects.length=0;select(null);status('New scene');}else if(a==='Delete'){if(selected){scene.remove(selected);objects.splice(objects.indexOf(selected),1);select(null);pushHistory();status('Deleted object')}}else if(a==='Duplicate'){if(selected){const c=selected.clone();c.material=selected.material.clone();c.position.x+=.5;c.name=selected.name+' Copy';scene.add(c);objects.push(c);select(c);pushHistory();}}else if(a==='Select All'){select(objects[0]);status(`${objects.length} object(s) in scene`)}else if(a==='Grid'){grid.visible=!grid.visible}else if(a==='Axes'){axes.visible=!axes.visible}else if(a==='Top View'){camera.position.set(0,12,0);orbit.target.set(0,0,0)}else if(a==='Front View'){camera.position.set(0,3,12);orbit.target.set(0,1,0)}else if(a==='Right View'){camera.position.set(12,3,0);orbit.target.set(0,1,0)}else if(a==='Home View'){camera.position.set(7,6,9);orbit.target.set(0,1,0)}else if(['Box','Sphere','Cylinder','Cone','Torus','Plane'].includes(a))addObject(a.toLowerCase());else if(a==='Save')saveScene();else if(a==='Export')exportScene();else status(a+' is in the editor roadmap');}
function saveScene(){localStorage.setItem('3d-builder-scene',JSON.stringify(snapshot()));status('Scene saved locally');}
function exportScene(){const data=JSON.stringify(snapshot(),null,2);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download='3d-builder-scene.json';a.click();URL.revokeObjectURL(a.href);status('Scene exported');}
document.querySelector('#saveBtn').onclick=saveScene;document.querySelector('#undoBtn').onclick=()=>status('Undo system reserved for full history module');document.querySelector('#redoBtn').onclick=()=>status('Redo system reserved for full history module');document.querySelector('#gridBtn').onclick=()=>grid.visible=!grid.visible;document.querySelector('#frameBtn').onclick=()=>{if(selected){const box=new THREE.Box3().setFromObject(selected);const c=box.getCenter(new THREE.Vector3());orbit.target.copy(c);camera.position.copy(c.clone().add(new THREE.Vector3(5,4,6)));}};
function status(t){document.querySelector('#statusText').textContent=t;}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)} addEventListener('resize',resize);resize();
function animate(){requestAnimationFrame(animate);orbit.update();renderer.render(scene,camera)} animate();
